### ISSUE TITLE
[WEB] Detail 페이지 컴포넌트 UI 구현 & 이벤트 등록

### ISSUE THREAD

**Issue by sang-gyeong** [boostcamp-2020/Project01-C-User-Event-Collector#117]
## Todo
- [ ] Detail Template
  - [ ] Detail Template UI
  - [ ] Template 이벤트 등록
- [ ] AlbumDetail
  - [ ] AlbumDetail UI
  - [ ] AlbumDetail 이벤트 등록
- [ ] ArtistDetail
  - [ ] ArtistDetail UI
  - [ ] ArtistDetail 이벤트 등록
- [ ] PlaylistDetail
  - [ ] PlaylistDetail UI
  - [ ] PlaylistDetail 이벤트 등록
- [ ] TrackDetail
  - [ ] TrackDetail UI
  - [ ] TrackDetail 이벤트 등록
