### ISSUE TITLE
[WEB] Magazine DB모델, API 구현

### ISSUE THREAD

**Issue by sang-gyeong** [boostcamp-2020/Project01-C-User-Event-Collector#121]
## Todo
- [ ] Magazine DB모델 구현
- [ ] GET Magazine API 구현
- [ ] Magazine 데이터 입력
