### ISSUE TITLE
[WEB] Next.js, TypeScript, 설정(webpack 등) 관련 스터디

### ISSUE THREAD

**Issue by thesulks** [boostcamp-2020/Project01-C-User-Event-Collector#35]
### Todo

- [x] dataFetch (isomorphic-unfetch, getStaticProps/getServerSideProps ) 
- [x] Config(typeScript, nextjs.config.json(webpack설정 - (tsx없이 typescript사용하기))
- [x] express, react(컴포넌트, tsx) <- TypeScript 적용시 고려해야할 부분들 정리하기

#### 여유되면...

- 본인이 맡지 않은 부분들도 공부해보기!
- nextJs + express + react + typescript 프로젝트 레퍼런스 찾아보기
